### ISSUE TITLE
Setup Git Flow

### ISSUE THREAD

**Issue by alunduil** [alunduil/etest#74]
Right now we're using the GitHub branching model but using git flow would provide an easier mechanism for dealing with release specifics while we figure out what our release artifacts should look like and how they're separate from feature changes.

## Subtasks

- [ ] Create develop branch
- [ ] Set develop branch to default
- [ ] Setup branch restrictions matching master on develop
- [ ] Ensure the contributing guidelines mention git flow

**Comment by LinoBigatti** [comment]
I believe we should leave this until the rest of the code runs correctly, as to leave master as a stable branch. However, it is a good idea.

**Comment by alunduil** [comment]
@LinoBigatti, do you think we should progress this or continue clean-up before making this change?

**Comment by LinoBigatti** [comment]
Would this create a lot of work on other branches? If not, then we can move on with this change imo.

**Comment by alunduil** [comment]
No, it should be a rebase onto the new develop branch (which would come off master).  We could throw in a rename of master to main as well, but I'm not in a hurry for that bit.

**Comment by alunduil** [comment]
I've added the default branch and updated it as the default branch.

**Comment by LinoBigatti** [comment]
> No, it should be a rebase onto the new develop branch (which would come off master). We could throw in a rename of master to main as well, but I'm not in a hurry for that bit.

Imo having master as a branch name isnt a super big issue, especially if it helps us avoid doing weird stuff on the current prs. If you want to do it go ahead, but maybe its better to leave it as is.
